---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r}
set.seed(1)

data("ny_noaa")

ny_noaa_clean = 
  ny_noaa %>% 
  na.omit() %>% 
  sample_n(10000) %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("year","month","day"), sep = "-") %>% 
  mutate(month = month.name[as.numeric(month)],
         year = as.numeric(year), 
         tmin = as.numeric(tmin, na.rm = TRUE),
         tmax = as.numeric(tmax, na.rm = TRUE), 
         prcp = prcp * 10 / 25.4,
         tmin = tmin / 10,  
         tmax = tmax / 10
         ) 
```

Column {data-width=500}
-----------------------------------------------------------------------
### Boxplot - Average Mex Temperature in May Between 1981 and 2010 

```{r}
ny_noaa_clean %>% 
  filter(month == "May") %>% 
  group_by(year, month, tmax) %>% 
  mutate(average_max_temp = mean(tmax, na.rm = TRUE)) %>% 
  plot_ly(x = ~year, y = ~average_max_temp, type = "box", 
           colors = "Set2")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Density Plot - Density of precipitation values greater than 0 and less than 10

```{r}
ny_noaa_prcp = 
  ny_noaa_clean %>% 
  filter(prcp > 0, prcp < 10) %>%  
  ggplot(aes(x = prcp)) + 
  geom_density() + 
  labs(
    title = "Density of precipitation values greater than 0 and less than 10",
    x = "Precipitation in mm",
    y = "Density") + 
  viridis::scale_color_viridis( 
    discrete = TRUE) 

ggplotly(ny_noaa_prcp)
```

### Scatterplot - Average Snowfall Between 1981 and 2010. 
```{r}
ny_noaa_clean %>%
  filter(snow > 0, snow < 100) %>% 
  group_by(year) %>% 
  mutate(average_snow = mean(snow, na.rm = TRUE)) %>% 
  plot_ly(x = ~year, y = ~average_snow, type = "scatter", mode = "markers",
        alpha = 0.5, 
        color = ~year)
```
